### ISSUE TITLE
Can't download recovery pkg. 

### ISSUE THREAD

**Issue by rudenik** [rtrouton/create_macos_recovery#1]
The URL (http://swcdn.apple.com/content/downloads/22/27/061-21534-A_KW51WMNF7J/js06knary954a9qquzljmax1xtqga4yaaz/SecUpd2019-005HighSierra.RecoveryHDUpdate.pkg) for the download of SecUpd2019-005HighSierra.RecoveryHDUpdate.pkg doesn't seem to work. 

If I try and hit that from a web browser I get a "not found" response. 
I tried to find a comparable download from apple, (closest I could get is this one, 
https://updates.cdn-apple.com/2019/cert/061-41807-20191024-e1f5cfe8-c906-4b7f-90b5-0ad98850cbd5/SecUpd2019-005HighSierra.dmg)
which doesn't contain the same tools that the script requires.

**Comment by rtrouton** [comment]
Now fixed. `SecUpd2019-005HighSierra.RecoveryHDUpdate.pkg` appears to have been retired in favor of `SecUpd2019-006HighSierra.RecoveryHDUpdate.pkg`.

**Comment by rudenik** [comment]
THANKS! Very much appreciated!
