### ISSUE TITLE
Failed to create 10.13.6 Recovery partition

### ISSUE THREAD

**Issue by flavoredframes** [rtrouton/create_macos_recovery#12]
Hi, I am getting the following error:

-- macOS installer is /Volumes/Data_Raid_0/Install macOS High Sierra.app
-- Installer application for macOS 10.13.6 detected. Proceeding....
Could not interpret boot device as either network or disk
Can't interpet EFI boot device
-- Target disk is .
-- Target filesystem is .
-- Downloading SecUpd2020-004HighSierra.RecoveryHDUpdate.pkg into /private/tmp
######################################################################## 100.0%
-- Failed to create 10.13.6 Recovery partition on .
--  does not have an APFS or HFS+ filesystem.

Any idea how I can fix this would be appreciated. 

Thanks

**Comment by rtrouton** [comment]
What is your boot drive? It seems that `diskutil` can't figure it out:

[https://github.com/rtrouton/create_macos_recovery/blob/master/create_macos_recovery.sh#L103](https://github.com/rtrouton/create_macos_recovery/blob/master/create_macos_recovery.sh#L103)

**Comment by flavoredframes** [comment]
After trying to solve the problem for about 3 hours and countless google attempts, I came across the solution to the problem shortly after this post. It is incredibly simple. You just have to select the boot drive under system preferences again and save it. I hope this helps those with the same problem.
