### ISSUE TITLE
Getting "command not found" errors

### ISSUE THREAD

**Issue by oldcar37** [rtrouton/create_macos_recovery#14]
I am running MacBook Pro late 2011 with OS 10.13.6 and OS 10.15.6 and Windows 7 Pro. Also have dosdude's GPU patch running. I am also using zsh shell in Terminal and Login. Have Terminal also emulating .sh shell. The file create_macos_recovery is also on desktop. Here is my Terminal window from session which I did on desktop:
![Screen Shot 2022-09-16 at 4 16 38 PM](https://user-images.githubusercontent.com/113716398/190726706-8bd7d758-9233-4363-b2fa-78746049b96b.png)
Anyone just pipe in with suggestions because I am a little new to this Github thing. I also have factory installed 256GB ssd and all volumes and container are APFS and GUID. All drives routinely run thru Disk Utility to detect any problems and Terminal show my OS 10.13.6 Recovery Partition and I can boot into recovery when OS High Sierra is startup Drive. Now I just need OS Catalina to have its own Recovery Partition and everything will be golden.

**Comment by rtrouton** [comment]
Try this command:

`sudo /Users/jamesmick/Desktop/create_macos_recovery.sh "/Applications/Install macOS Catalina.app"`

**Comment by oldcar37** [comment]
Thanks for your reply rtrouton, I have already tried that and received Terminal output dquote>. I did some checking and dquote> refers to double quotations and the response would to enter another double quote argument or use single quotes instead or enter “ with keystroke. I will give results of Terminal output using single quotes later.

**Comment by oldcar37** [comment]
Hi rtrouton, here is Terminal output from you suggestion
![Screen Shot 2022-09-18 at 7 36 41 PM](https://user-images.githubusercontent.com/113716398/190933057-cbb8f933-e3c1-4547-bac9-635794fb3ffe.png)
I used single quotes instead of double and did not receive the >dquote from Terminal.

**Comment by oldcar37** [comment]
Success!!!! Here is my Terminal output after running rtrouton's/create_macos_recovery. I used Xcode to get this shell doc.
[create_macos_recovery.sh.pdf](https://github.com/rtrouton/create_macos_recovery/files/9600241/create_macos_recovery.sh.pdf)
[Terminal Saved Output.pdf](https://github.com/rtrouton/create_macos_recovery/files/9600254/Terminal.Saved.Output.pdf)

**Comment by oldcar37** [comment]
If anyone would like copies of code just email/message me, happy to share.

**Comment by rtrouton** [comment]
I'm glad to see you figured it out. Closing this issue.

**Comment by ssssamstrup** [comment]
How did you get it to work @oldcar37 ? I'm running to the same issue. Running MacOS Mojave 10.14.6 (with no other OSs installed.

**Comment by oldcar37** [comment]
> How did you get it to work @oldcar37 ? I'm running to the same issue. Running MacOS Mojave 10.14.6 (with no other OSs installed.

Would a copy of input in Terminal help you out, as you have not mentioned weather you tried or not.

**Comment by ssssamstrup** [comment]
I've tried all the inputs you've mentioned above and when using sudo without, with " and with ' I get a »command not found« error.

**Comment by ssssamstrup** [comment]
I just saw in another post something about there could being a problem with HFS+ volumes - however when I searched for more info, people said that running Mojave on HFS+ was not a problem.

My volume is HFS+. Would that make a difference?
