### ISSUE TITLE
SecUpd2020-001HighSierra.RecoveryHDUpdate Not Found

### ISSUE THREAD

**Issue by danielnovello** [rtrouton/create_macos_recovery#6]
`SecUpd2020-001HighSierra.RecoveryHDUpdate.pkg` Not found either now.

Painful how they keep changing things.

**Comment by danielnovello** [comment]
Its changed to `http://swcdn.apple.com/content/downloads/63/02/061-90748-A_MQ4MTMMXYW/jtw6sxlorttnetfsu9wpu0rqubsa55bskp/SecUpd2020-002HighSierra.RecoveryHDUpdate.pkg`

**Comment by milkmansson** [comment]
> Its changed to `http://swcdn.apple.com/content/downloads/63/02/061-90748-A_MQ4MTMMXYW/jtw6sxlorttnetfsu9wpu0rqubsa55bskp/SecUpd2020-002HighSierra.RecoveryHDUpdate.pkg`

btw - the script, upon this failure, produces a file called secupd.....pkg with the text "file not found." in it if this fails... maybe we could include a check to curl errorlevels or sth, to see if it completed well before proceeding?

Thanks for this djquazzi.  Adjusted and put in script and is running perfectly.  Is a sizeable download btw - maybe make the cleanup of the downloaded PKG optional in case of issues where you need it again?

Thanks for the awesome work rtrouton!  ACE!

**Comment by GuilhermePoyares** [comment]
Looks like it changed again, I couldn't find it anywhere, I am using your script with Catalina 10.15.5
Can you help?
