### ISSUE TITLE
pkg no longer available

### ISSUE THREAD

**Issue by bezik46** [rtrouton/create_macos_recovery#8]
SecUpd2020-003HighSierra.RecoveryHDUpdate.pkg is not there
Maybe it would be "better" to use SecUpd2020-003Mojave.RecoveryHDUpdate.pkg ?

**Comment by daydr3am3r** [comment]
The new link is: http://swcdn.apple.com/content/downloads/14/54/001-08570-A_XCP1PVIXQK/xg4hvg6zgpoxonqkgiw2e2cqo1c0isl97q/SecUpd2020-004HighSierra.RecoveryHDUpdate.pkg

It would make sense to have additional logic which would:
1. Download https://swscan.apple.com/content/catalogs/others/index-10.13-1.sucatalog
2. Look for the string HighSierra.RecoveryHDUpdate.pkg
3. Populate the _recovery_package_ and _recovery_download_ variables accordingly
